name = "kakaomacro-license"
main = "src/index.ts"
compatibility_date = "2026-10-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "kakaomacro-license"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
migrations_dir = "migrations"

[triggers]
crons = ["17 * * * *"]
