from pathlib import Path

p = Path('app/src/main/java/com/local/kakaoautosender/MainActivityV4.java')
s = p.read_text(encoding='utf-8')

def r(old, new, n=1):
    global s
    c = s.count(old)
    if c != n:
        raise SystemExit(f'dashboard replace mismatch: expected {n}, got {c}: {old[:120]!r}')
    s = s.replace(old, new, n)

r('    private TextView masterStatus;\n    private TextView systemStatus;',
  '    private TextView masterStatus;\n    private TextView masterBadge;\n    private TextView systemStatus;')

r('        statusHeader.addView(statusCaption, weight());\n        statusHeader.addView(pill("PROTECTED", Color.rgb(25, 49, 42), Color.rgb(122, 231, 176)));\n        masterCard.addView(statusHeader);',
  '        statusHeader.addView(statusCaption, weight());\n        masterBadge = pill("READY", Color.rgb(32, 43, 68), Color.rgb(172, 190, 255));\n        statusHeader.addView(masterBadge);\n        masterCard.addView(statusHeader);')

old = '''        ArrayList<MultiRoomStore.Profile> profiles = MultiRoomStore.list(this);\n\n        masterStatus.setText(active ? "자동전송 실행 중" : "자동전송 대기");\n        masterStatus.setTextColor(active ? GREEN : TEXT);\n        StringBuilder system = new StringBuilder();\n        system.append("라이선스 ").append(LicenseManager.shortStatus(this));\n        system.append("  ·  알림 접근 ").append(access ? "정상" : "권한 필요");\n        system.append("  ·  리스너 ").append(listener ? "정상" : "대기");\n        if (Build.VERSION.SDK_INT >= 31) system.append("\\n정확 시각 ").append(exact ? "사용 가능" : "선택사항 · 근사 시각 사용");\n        system.append("  ·  연결 방 ").append(profiles.size()).append("개");\n        String notice = LicenseManager.updateNotice(this);\n        if (notice != null && !notice.trim().isEmpty()) system.append("\\n").append(notice.trim());\n        systemStatus.setText(system.toString());\n\n        startButton.setEnabled(!active);\n        stopButton.setEnabled(active);\n        startButton.setAlpha(active ? 0.46f : 1f);\n        stopButton.setAlpha(active ? 1f : 0.46f);'''
new = '''        ArrayList<MultiRoomStore.Profile> profiles = MultiRoomStore.list(this);\n        int enabled = MultiRoomStore.enabledCount(this);\n        int ready = MultiRoomStore.readyCount(this);\n        int usable = 0;\n        for (MultiRoomStore.Profile p : profiles) {\n            if (p.enabled && RoomMediaStore.hasPayload(this, p)) usable++;\n        }\n\n        if (active && enabled > 0 && ready < enabled) {\n            masterStatus.setText("자동전송 실행 중 · 연결 대기");\n            masterStatus.setTextColor(AMBER);\n            stylePill(masterBadge, "WAIT", Color.rgb(55, 45, 27), AMBER);\n        } else if (active) {\n            masterStatus.setText("자동전송 실행 중");\n            masterStatus.setTextColor(GREEN);\n            stylePill(masterBadge, "LIVE", Color.rgb(25, 49, 42), Color.rgb(122, 231, 176));\n        } else if (!access) {\n            masterStatus.setText("알림 접근 권한이 필요합니다");\n            masterStatus.setTextColor(AMBER);\n            stylePill(masterBadge, "SETUP", Color.rgb(55, 45, 27), AMBER);\n        } else if (usable == 0) {\n            masterStatus.setText("방 설정을 완료하세요");\n            masterStatus.setTextColor(TEXT);\n            stylePill(masterBadge, "SETUP", Color.rgb(45, 49, 59), Color.rgb(180, 190, 211));\n        } else {\n            masterStatus.setText("자동전송 준비됨");\n            masterStatus.setTextColor(TEXT);\n            stylePill(masterBadge, "READY", Color.rgb(32, 43, 68), Color.rgb(172, 190, 255));\n        }\n\n        StringBuilder system = new StringBuilder();\n        system.append("라이선스 ").append(LicenseManager.shortStatus(this));\n        system.append("  ·  알림 접근 ").append(access ? "정상" : "권한 필요");\n        system.append("\\n카카오 연결 ").append(listener ? "정상" : "대기");\n        if (Build.VERSION.SDK_INT >= 31) {\n            system.append("  ·  예약 정확도 ").append(exact ? "정확 시각" : "근사 시각");\n        }\n        system.append("  ·  연결 방 ").append(profiles.size()).append("개");\n        String notice = LicenseManager.updateNotice(this);\n        if (notice != null && !notice.trim().isEmpty()) system.append("\\n").append(notice.trim());\n        systemStatus.setText(system.toString());\n        systemStatus.setTextColor(!access ? AMBER : Color.rgb(181, 191, 210));\n\n        startButton.setEnabled(!active && access && usable > 0);\n        stopButton.setEnabled(active);\n        if (active) startButton.setText("자동전송 실행 중");\n        else if (!access) startButton.setText("알림 접근 필요");\n        else if (usable == 0) startButton.setText("방 설정을 완료하세요");\n        else startButton.setText("자동전송 시작");\n        startButton.setAlpha(startButton.isEnabled() ? 1f : 0.46f);\n        stopButton.setAlpha(active ? 1f : 0.46f);'''
r(old, new)

r('        int ready = MultiRoomStore.readyCount(this);\n        int enabled = MultiRoomStore.enabledCount(this);\n        long next = MultiRoomStore.nextDueAt(this);',
  '        long next = MultiRoomStore.nextDueAt(this);')

r('''        TextView meta = text(count + next + failure, 11, false, Color.rgb(133, 146, 169));\n        card.addView(meta, top(8));\n\n        LinearLayout actions = new LinearLayout(this);''',
  '''        TextView meta = text(count + next + failure, 11, false, Color.rgb(133, 146, 169));\n        card.addView(meta, top(8));\n\n        String recent = p.lastSuccessAt > 0\n                ? "최근 성공  ·  " + formatDateTime(p.lastSuccessAt)\n                : p.failureStreak > 0\n                    ? "최근 전송 확인 필요  ·  실패 " + p.failureStreak + "회"\n                    : "최근 전송 기록 없음";\n        TextView recentView = text(recent, 10, false,\n                p.failureStreak > 0 ? AMBER : Color.rgb(112, 126, 151));\n        card.addView(recentView, top(6));\n\n        LinearLayout actions = new LinearLayout(this);''')

old = '''            boolean existing = !room.isEmpty() && !MultiRoomStore.findByActualName(this, room).isEmpty();\n            LinearLayout rowTop = new LinearLayout(this);\n            rowTop.setOrientation(LinearLayout.HORIZONTAL);\n            rowTop.setGravity(Gravity.CENTER_VERTICAL);\n            TextView name = text(room.isEmpty() ? "방 이름 미확인" : room, 15, true, TEXT);\n            name.setMaxLines(2);\n            rowTop.addView(name, weight());\n            rowTop.addView(pill(manual ? "확인" : existing ? "복구" : "연결",\n                    existing ? Color.rgb(25, 49, 42) : Color.rgb(29, 38, 65),\n                    existing ? GREEN : Color.rgb(180, 195, 255)));\n            row.addView(rowTop);\n            String meta = manual ? "알림에 표시된 방 이름을 확인한 뒤 연결합니다."\n                    : existing ? "기존 등록 방 · 현재 답장 연결만 복구합니다."\n                    : "새 방 후보 · 선택하면 방별 설정 화면으로 이동합니다.";\n            row.addView(text(meta, 11, false, existing ? GREEN : Color.rgb(125, 139, 166)), top(6));'''
new = '''            int existingCount = room.isEmpty() ? 0 : MultiRoomStore.findByActualName(this, room).size();\n            boolean existing = existingCount == 1;\n            boolean conflict = existingCount > 1;\n            LinearLayout rowTop = new LinearLayout(this);\n            rowTop.setOrientation(LinearLayout.HORIZONTAL);\n            rowTop.setGravity(Gravity.CENTER_VERTICAL);\n            TextView name = text(room.isEmpty() ? "방 이름 미확인" : room, 15, true, TEXT);\n            name.setMaxLines(2);\n            rowTop.addView(name, weight());\n            String badge = manual ? "확인" : conflict ? "중복 확인" : existing ? "복구" : "연결";\n            int badgeBg = conflict ? Color.rgb(58, 31, 36)\n                    : existing ? Color.rgb(25, 49, 42) : Color.rgb(29, 38, 65);\n            int badgeFg = conflict ? RED : existing ? GREEN : Color.rgb(180, 195, 255);\n            rowTop.addView(pill(badge, badgeBg, badgeFg));\n            row.addView(rowTop);\n            String meta = manual ? "알림에 표시된 방 이름을 확인한 뒤 연결합니다."\n                    : conflict ? "같은 이름으로 등록된 방이 여러 개 있어 자동 연결을 차단합니다."\n                    : existing ? "기존 등록 방 · 현재 답장 연결만 복구합니다."\n                    : "새 방 후보 · 선택하면 방별 설정 화면으로 이동합니다.";\n            row.addView(text(meta, 11, false, conflict ? RED : existing ? GREEN : Color.rgb(125, 139, 166)), top(6));\n            row.setContentDescription((room.isEmpty() ? "방 이름 미확인" : room) + " · " + badge);'''
r(old, new)

r('''        ArrayList<MultiRoomStore.Profile> existing = MultiRoomStore.findByActualName(this, actualName);\n        if (existing.size() == 1) {''',
  '''        ArrayList<MultiRoomStore.Profile> existing = MultiRoomStore.findByActualName(this, actualName);\n        if (existing.size() > 1) {\n            new AlertDialog.Builder(this)\n                    .setTitle("같은 이름의 등록 방이 여러 개 있습니다")\n                    .setMessage("오배송 방지를 위해 자동으로 연결하지 않았습니다. 기존 중복 방을 먼저 정리한 뒤 다시 시도해 주세요.")\n                    .setPositiveButton("확인", null)\n                    .show();\n            return;\n        }\n        if (existing.size() == 1) {''')

r('''                    String actualName = input.getText().toString().trim();\n                    if (actualName.isEmpty()) { toast("방 이름을 입력해 주세요."); return; }\n                    String routeAlias = "route-" + UUID.randomUUID();\n                    if (!KakaoNotificationListener.bindRecentTokenToRoom(this, entry.token, routeAlias)) {\n                        toast("알림 세션이 만료되었습니다."); return;\n                    }\n                    MultiRoomStore.Profile p = new MultiRoomStore.Profile(routeAlias);\n                    p.actualRoomName = actualName;\n                    p.displayName = actualName;\n                    MultiRoomStore.upsert(this, p);\n                    openEditor(routeAlias);''',
  '''                    String actualName = input.getText().toString().trim();\n                    if (actualName.isEmpty()) { toast("방 이름을 입력해 주세요."); return; }\n                    connectCandidate(entry, actualName);''')

old = '''    private void startAuthorized() {\n        if (!isNotificationAccessEnabled()) {\n            toast("알림 접근 권한을 먼저 허용해 주세요.");\n            return;\n        }\n        ArrayList<MultiRoomStore.Profile> profiles = MultiRoomStore.list(this);\n        int usable = 0;\n        int ready = 0;\n        for (MultiRoomStore.Profile p : profiles) {\n            if (!p.enabled || !RoomMediaStore.hasPayload(this, p)) continue;\n            usable++;\n            if (KakaoNotificationListener.hasLiveSession(p.room)) ready++;\n        }\n        if (usable == 0) {\n            toast("사용 중이며 메시지가 저장된 방이 없습니다.");\n            return;\n        }\n        synchronized (DeliveryGate.LOCK) {\n            if (!LicenseManager.isUsable(this)) { LicenseManager.route(this); return; }\n            Prefs.p(this).edit().putBoolean(Prefs.KEY_ACTIVE, true).commit();\n        }\n        MultiRoomStore.setAllNextFromNow(this);\n        SendScheduler.scheduleNext(this);\n        Prefs.setStatus(this, "전체 자동전송 시작 · " + usable + "개 방 · 즉시 연결 " + ready + "개");\n        refreshUi();\n        toast(ready == usable ? "자동전송을 시작했습니다." : "자동전송을 시작했습니다. 연결 대기 방은 새 알림이 오면 복구됩니다.");\n    }'''
new = '''    private void startAuthorized() {\n        if (!isNotificationAccessEnabled()) {\n            toast("알림 접근 권한을 먼저 허용해 주세요.");\n            return;\n        }\n        ArrayList<MultiRoomStore.Profile> profiles = MultiRoomStore.list(this);\n        int usable = 0;\n        int ready = 0;\n        for (MultiRoomStore.Profile p : profiles) {\n            if (!p.enabled || !RoomMediaStore.hasPayload(this, p)) continue;\n            usable++;\n            if (KakaoNotificationListener.hasLiveSession(p.room)) ready++;\n        }\n        if (usable == 0) {\n            toast("사용 중이며 전송 내용이 저장된 방이 없습니다.");\n            return;\n        }\n        final int usableCount = usable;\n        final int readyCount = ready;\n        if (ready < usable) {\n            new AlertDialog.Builder(this)\n                    .setTitle("일부 방이 연결 대기 중입니다")\n                    .setMessage("사용할 방 " + usable + "개 중 현재 " + ready + "개가 즉시 전송 가능합니다.\\n\\n연결 대기 방은 해당 카카오 방에서 새 메시지를 받으면 복구됩니다.")\n                    .setPositiveButton("대기 방 포함 시작", (d, w) -> commitStart(usableCount, readyCount))\n                    .setNegativeButton("취소", null)\n                    .show();\n            return;\n        }\n        commitStart(usable, ready);\n    }\n\n    private void commitStart(int usable, int ready) {\n        synchronized (DeliveryGate.LOCK) {\n            if (!LicenseManager.isUsable(this)) { LicenseManager.route(this); return; }\n            Prefs.p(this).edit().putBoolean(Prefs.KEY_ACTIVE, true).commit();\n        }\n        MultiRoomStore.setAllNextFromNow(this);\n        SendScheduler.scheduleNext(this);\n        Prefs.setStatus(this, "전체 자동전송 시작 · " + usable + "개 방 · 즉시 연결 " + ready + "개");\n        refreshUi();\n        toast(ready == usable ? "자동전송을 시작했습니다." : "자동전송을 시작했습니다. 연결 대기 방은 새 알림이 오면 복구됩니다.");\n    }'''
r(old, new)

r('''    private TextView pill(String value, int bg, int fg) {\n        TextView v = text(value, 10, true, fg);\n        v.setGravity(Gravity.CENTER);\n        v.setPadding(dp(9), dp(6), dp(9), dp(6));\n        v.setBackground(roundStroke(bg, Color.rgb(62, 73, 96), 14));\n        return v;\n    }''',
  '''    private TextView pill(String value, int bg, int fg) {\n        TextView v = text(value, 10, true, fg);\n        v.setGravity(Gravity.CENTER);\n        v.setPadding(dp(9), dp(6), dp(9), dp(6));\n        v.setBackground(roundStroke(bg, Color.rgb(62, 73, 96), 14));\n        return v;\n    }\n\n    private void stylePill(TextView view, String value, int bg, int fg) {\n        if (view == null) return;\n        view.setText(value);\n        view.setTextColor(fg);\n        view.setBackground(roundStroke(bg, Color.rgb(62, 73, 96), 14));\n    }''')

p.write_text(s, encoding='utf-8')
