from pathlib import Path

p = Path('app/src/main/java/com/local/kakaoautosender/RoomEditorActivity.java')
s = p.read_text(encoding='utf-8')

def r(old, new, n=1):
    global s
    c = s.count(old)
    if c != n:
        raise SystemExit(f'editor replace mismatch: expected {n}, got {c}: {old[:120]!r}')
    s = s.replace(old, new, n)

r('import android.provider.OpenableColumns;\nimport android.text.InputType;',
  'import android.provider.OpenableColumns;\nimport android.text.Editable;\nimport android.text.InputType;\nimport android.text.TextWatcher;')

r('''    private TextView connectionStatus;\n    private TextView nextPreview;\n    private TextView imageStatus;\n    private android.widget.ImageView imagePreview;''',
  '''    private TextView connectionStatus;\n    private TextView executionStatus;\n    private TextView nextPreview;\n    private TextView imageStatus;\n    private TextView messageCount;\n    private TextView dirtyStatus;\n    private Button saveButton;\n    private android.widget.ImageView imagePreview;\n    private boolean loading;\n    private boolean dirty;''')

r('''        if (MultiRoomStore.get(this, routeAlias) == null) { finish(); return; }\n        setContentView(buildUi());\n        loadProfile();''',
  '''        if (MultiRoomStore.get(this, routeAlias) == null) { finish(); return; }\n        setContentView(buildUi());\n        loading = true;\n        loadProfile();\n        loading = false;\n        installDirtyTracking();\n        setDirty(false);''')

r('''    @Override protected void onResume() {\n        super.onResume();\n        KakaoNotificationListener.requestRefresh();\n        refreshConnection();\n        refreshMedia();\n        refreshNextPreview();\n    }''',
  '''    @Override protected void onResume() {\n        super.onResume();\n        KakaoNotificationListener.requestRefresh();\n        refreshConnection();\n        refreshMedia();\n        refreshNextPreview();\n    }\n\n    @Override public void onBackPressed() {\n        requestClose();\n    }''')

r('''        connectionStatus = text("", 14, true, TEXT);\n        connectionCard.addView(connectionStatus, top(12));\n        Button reconnect = secondaryButton("이 방 연결 다시 확인");''',
  '''        connectionStatus = text("", 14, true, TEXT);\n        connectionCard.addView(connectionStatus, top(12));\n        executionStatus = text("", 11, false, Color.rgb(130, 143, 166));\n        executionStatus.setLineSpacing(0, 1.14f);\n        connectionCard.addView(executionStatus, top(7));\n        Button reconnect = secondaryButton("이 방 연결 다시 확인");''')

r('''        messageInput = edit("자동으로 보낼 메시지", true);\n        root.addView(messageInput, top(10));''',
  '''        messageInput = edit("자동으로 보낼 메시지", true);\n        root.addView(messageInput, top(10));\n        messageCount = text("0자", 10, false, Color.rgb(112, 126, 151));\n        messageCount.setGravity(Gravity.END);\n        root.addView(messageCount, top(5));''')

r('''        modes.setOnCheckedChangeListener((group, checkedId) -> {\n            updateScheduleVisibility();\n            refreshNextPreview();\n        });''',
  '''        modes.setOnCheckedChangeListener((group, checkedId) -> {\n            updateScheduleVisibility();\n            refreshNextPreview();\n            markDirty();\n        });''')

r('        unlimitedCheck.setOnCheckedChangeListener((b, checked) -> dailyLimitInput.setEnabled(!checked));',
  '''        unlimitedCheck.setOnCheckedChangeListener((b, checked) -> {\n            dailyLimitInput.setEnabled(!checked);\n            markDirty();\n        });''')

r('''        LinearLayout actionCard = card(SURFACE_2, BORDER, 18);\n        TextView actionTitle = text("변경 사항", 11, true, Color.rgb(128, 142, 169));\n        actionTitle.setLetterSpacing(0.06f);\n        actionCard.addView(actionTitle);\n        Button save = primaryButton("설정 저장");\n        save.setOnClickListener(v -> saveProfile(true));\n        actionCard.addView(save, top(11));\n        Button test = positiveSecondaryButton("지금 1회 테스트 전송");\n        test.setOnClickListener(v -> testSend());\n        actionCard.addView(test, top(8));\n        Button back = secondaryButton("대시보드로 돌아가기");\n        back.setOnClickListener(v -> finish());\n        actionCard.addView(back, top(8));''',
  '''        LinearLayout actionCard = card(SURFACE_2, BORDER, 18);\n        TextView actionTitle = text("변경 사항", 11, true, Color.rgb(128, 142, 169));\n        actionTitle.setLetterSpacing(0.06f);\n        actionCard.addView(actionTitle);\n        dirtyStatus = text("모든 변경 사항이 저장되었습니다.", 11, false, Color.rgb(119, 132, 156));\n        actionCard.addView(dirtyStatus, top(6));\n        saveButton = primaryButton("설정 저장");\n        saveButton.setOnClickListener(v -> saveProfile(true));\n        actionCard.addView(saveButton, top(11));\n        Button test = positiveSecondaryButton("지금 1회 테스트 전송");\n        test.setOnClickListener(v -> testSend());\n        actionCard.addView(test, top(8));\n        Button back = secondaryButton("대시보드로 돌아가기");\n        back.setOnClickListener(v -> requestClose());\n        actionCard.addView(back, top(8));''')

r('''        TextView footer = text("설정 저장 전에는 기존 자동전송 설정이 변경되지 않습니다.", 11, false, Color.rgb(105, 118, 141));''',
  '''        TextView footer = text("메시지·스케줄·사용 여부는 ‘설정 저장’ 전까지 적용되지 않습니다. 사진 첨부는 선택 즉시 이 방에 보관됩니다.", 11, false, Color.rgb(105, 118, 141));''')

r('''        Prefs.setStatus(this, "방 설정 저장: " + p.title() + " · " + MultiRoomStore.scheduleSummary(p));\n        refreshNextPreview();\n        if (notify) {''',
  '''        Prefs.setStatus(this, "방 설정 저장: " + p.title() + " · " + MultiRoomStore.scheduleSummary(p));\n        refreshNextPreview();\n        setDirty(false);\n        if (notify) {''')

old = '''    private void testSend() {\n        if (!saveProfile(false)) return;\n        MultiRoomStore.Profile p = MultiRoomStore.get(this, routeAlias);\n        if (!RoomMediaStore.hasPayload(this, p)) {\n            toast("보낼 메시지를 입력해 주세요.");\n            return;\n        }\n        if (!KakaoNotificationListener.hasLiveSession(routeAlias)) {\n            toast("이 방 연결이 없습니다. 방에서 새 메시지를 받은 뒤 ‘연결 다시 확인’을 눌러 주세요.");\n            return;\n        }\n        RoomMediaStore.Media media = RoomMediaStore.get(this, routeAlias);\n        String mediaLine = media.hasImage() ? "\\n사진: " + (media.name.isEmpty() ? "첨부됨" : media.name) : "";\n        new AlertDialog.Builder(this)\n                .setTitle("1회 테스트 전송")\n                .setMessage(p.title() + "\\n\\n" + p.message + mediaLine)\n                .setPositiveButton("전송", (d, w) -> {\n                    LicenseManager.runAuthorized(this, () -> {\n                        boolean ok = KakaoMessageSender.send(this, routeAlias, p.message, media);\n                        String error = KakaoMessageSender.lastError();\n                        Prefs.setStatus(this, ok ? "수동 전송 성공: " + p.title()\n                                : "수동 전송 실패: " + p.title() + " · " + error);\n                        toast(ok ? "테스트 전송에 성공했습니다." : "전송 실패: " + error);\n                        refreshConnection();\n                    });\n                })\n                .setNegativeButton("취소", null)\n                .show();\n    }'''
new = '''    private void testSend() {\n        MultiRoomStore.Profile p = MultiRoomStore.get(this, routeAlias);\n        if (p == null) return;\n        String draftMessage = messageInput.getText().toString();\n        RoomMediaStore.Media media = RoomMediaStore.get(this, routeAlias);\n        if (draftMessage.trim().isEmpty() && !media.hasImage()) {\n            toast("보낼 메시지 또는 사진을 먼저 설정해 주세요.");\n            return;\n        }\n        if (!KakaoNotificationListener.hasLiveSession(routeAlias)) {\n            toast("이 방 연결이 없습니다. 방에서 새 메시지를 받은 뒤 ‘연결 다시 확인’을 눌러 주세요.");\n            return;\n        }\n        String mediaLine = media.hasImage() ? "\\n사진: " + (media.name.isEmpty() ? "첨부됨" : media.name) : "";\n        String draftLine = dirty\n                ? "\\n\\n저장하지 않은 현재 입력값으로만 테스트합니다. 자동전송 설정에는 저장되지 않습니다."\n                : "";\n        new AlertDialog.Builder(this)\n                .setTitle("1회 테스트 전송")\n                .setMessage(p.title() + "\\n\\n" + (draftMessage.trim().isEmpty() ? "텍스트 없음" : draftMessage) + mediaLine + draftLine)\n                .setPositiveButton("전송", (d, w) -> LicenseManager.runAuthorized(this, () -> {\n                    boolean ok = KakaoMessageSender.send(this, routeAlias, draftMessage, media);\n                    String error = KakaoMessageSender.lastError();\n                    Prefs.setStatus(this, ok ? "수동 전송 성공: " + p.title()\n                            : "수동 전송 실패: " + p.title() + " · " + error);\n                    toast(ok ? "테스트 전송에 성공했습니다." : "전송 실패: " + error);\n                    refreshConnection();\n                }))\n                .setNegativeButton("취소", null)\n                .show();\n    }'''
r(old, new)

r('''        connectionStatus.setText(live ? "●  연결됨 · 지금 전송 가능"\n                : stored ? "●  복구 대기 · 새 알림이 오면 자동 복구"\n                : "●  연결 필요 · 이 방에서 새 메시지를 받아 주세요");\n        connectionStatus.setTextColor(live ? GREEN : stored ? AMBER : RED);\n    }''',
  '''        connectionStatus.setText(live ? "●  연결됨 · 지금 전송 가능"\n                : stored ? "●  복구 대기 · 새 알림이 오면 자동 복구"\n                : "●  연결 필요 · 이 방에서 새 메시지를 받아 주세요");\n        connectionStatus.setTextColor(live ? GREEN : stored ? AMBER : RED);\n        MultiRoomStore.Profile p = MultiRoomStore.get(this, routeAlias);\n        if (executionStatus != null && p != null) {\n            if (p.lastSuccessAt > 0) {\n                executionStatus.setText("최근 성공  ·  " + new SimpleDateFormat("MM-dd HH:mm:ss", Locale.KOREA).format(new Date(p.lastSuccessAt))\n                        + (p.failureStreak > 0 ? "  ·  이후 실패 " + p.failureStreak + "회" : ""));\n                executionStatus.setTextColor(p.failureStreak > 0 ? AMBER : Color.rgb(130, 143, 166));\n            } else if (p.failureStreak > 0) {\n                executionStatus.setText("최근 전송 실패 " + p.failureStreak + "회 · 테스트 전송으로 상태를 확인해 주세요.");\n                executionStatus.setTextColor(AMBER);\n            } else {\n                executionStatus.setText("아직 전송 기록이 없습니다. 저장 후 1회 테스트를 권장합니다.");\n                executionStatus.setTextColor(Color.rgb(130, 143, 166));\n            }\n        }\n    }''')

insert_before = '''    private int parseInt(String s, int fallback) {\n        try { return Integer.parseInt(s.trim()); } catch (Exception e) { return fallback; }\n    }'''
helpers = '''    private void installDirtyTracking() {\n        TextWatcher watcher = new TextWatcher() {\n            @Override public void beforeTextChanged(CharSequence s, int start, int count, int after) {}\n            @Override public void onTextChanged(CharSequence s, int start, int before, int count) {\n                updateMessageCount();\n                refreshNextPreview();\n                markDirty();\n            }\n            @Override public void afterTextChanged(Editable s) {}\n        };\n        messageInput.addTextChangedListener(watcher);\n        intervalInput.addTextChangedListener(watcher);\n        timesInput.addTextChangedListener(watcher);\n        dailyLimitInput.addTextChangedListener(watcher);\n        enabledCheck.setOnCheckedChangeListener((b, checked) -> markDirty());\n        updateMessageCount();\n    }\n\n    private void updateMessageCount() {\n        if (messageCount == null || messageInput == null) return;\n        int length = messageInput.getText() == null ? 0 : messageInput.getText().length();\n        messageCount.setText(length + "자");\n        messageCount.setTextColor(length > 1000 ? AMBER : Color.rgb(112, 126, 151));\n    }\n\n    private void markDirty() {\n        if (loading) return;\n        setDirty(true);\n    }\n\n    private void setDirty(boolean value) {\n        dirty = value;\n        if (dirtyStatus != null) {\n            dirtyStatus.setText(value ? "저장하지 않은 변경 사항이 있습니다." : "모든 변경 사항이 저장되었습니다.");\n            dirtyStatus.setTextColor(value ? AMBER : Color.rgb(119, 132, 156));\n        }\n        if (saveButton != null) {\n            saveButton.setText(value ? "변경 사항 저장" : "설정 저장됨");\n            saveButton.setAlpha(value ? 1f : 0.72f);\n        }\n    }\n\n    private void requestClose() {\n        if (!dirty) {\n            finish();\n            return;\n        }\n        new AlertDialog.Builder(this)\n                .setTitle("저장하지 않은 변경 사항이 있습니다")\n                .setMessage("대시보드로 돌아가면 메시지·스케줄·사용 여부의 변경 사항이 사라집니다.")\n                .setPositiveButton("저장 후 돌아가기", (d, w) -> {\n                    if (saveProfile(true)) finish();\n                })\n                .setNeutralButton("저장하지 않기", (d, w) -> finish())\n                .setNegativeButton("계속 편집", null)\n                .show();\n    }\n\n'''+insert_before
r(insert_before, helpers)

p.write_text(s, encoding='utf-8')
